name: example
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit: ^3.0.0
  json_annotation: ^4.0.1
  aqueduct_doc_to_obj:
    git:
      url: https://github.com/PavelS0/aqueduct_document_to_object.git
      ref: release-2.1.0
      path: annotation

dev_dependencies:
  json_serializable: ^4.1.0
  build_runner: ^1.12.0
  aqueduct_doc_to_obj_generator:
    git:
      url: https://github.com/PavelS0/aqueduct_document_to_object.git
      ref: release-2.1.0
      path: generator
