name: example

dependencies:
  aqueduct: ^4.0.0-b1
  json_annotation: ^3.1.0
  aqueduct_doc_to_obj:
    git:
      url: https://github.com/PavelS0/aqueduct_document_to_object.git
      ref: beta-0.0.5
      path: annotation

dev_dependencies:
  json_serializable: ^3.0.0
  build_runner: ^1.10.0
  aqueduct_doc_to_obj_generator:
    git:
      url: https://github.com/PavelS0/aqueduct_document_to_object.git
      ref: beta-0.0.5
      path: generator
