name: example
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit: ^2.0.0-b1
  json_annotation: ^4.0.1
  aqueduct_doc_to_obj:
    git:
      url: https://github.com/PavelS0/aqueduct_document_to_object.git
      ref: beta-0.0.5
      path: annotation

dev_dependencies:
  json_serializable: ^4.1.0
  build_runner: ^1.12.0
  aqueduct_doc_to_obj_generator:
    git:
      url: https://github.com/PavelS0/aqueduct_document_to_object.git
      ref: beta-0.0.5
      path: generator
