name: aqueduct_doc_to_obj_generator
description: Generator for aqueduct_doc_to_obj package.
version: 2.1.0
author: Pavel Snitko <brian57reg@gmail.com>
homepage: https://github.com/PavelS0/aqueduct_document_to_object
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.3.0
  build: ^2.0.0
  conduit: ^3.0.0
  source_gen: ^1.0.0 
  aqueduct_doc_to_obj:
    git:
      url: https://github.com/PavelS0/aqueduct_document_to_object.git
      ref: release-2.1.0
      path: annotation

dev_dependencies:
  build_runner: ^1.12.2


#dependency_overrides:
#  aqueduct_doc_to_obj:
#    path: ../annotation/
