name: aqueduct_doc_to_obj
description: Annotations for aqueduct_doc_to_obj package.
version: 0.0.3
author: Pavel Snitko <brian57reg@gmail.com>
homepage: https://github.com/PavelS0/aqueduct_document_to_object

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  build_config: ^0.4.2
  aqueduct: ^4.0.0-b1
  json_annotation: ^3.1.0
  analyzer: ^0.40.0
  

dev_dependencies:
  test: ^1.15.5
  json_serializable: ^3.0.0
  build_runner: ^1.10.4
  aqueduct_doc_to_obj_generator:
    git:
      url: https://github.com/PavelS0/aqueduct_document_to_object.git
      ref: main
      path: generator

#dependency_overrides:
#  aqueduct_doc_to_obj_generator:
#    path: ../generator/